DROP DATABASE BLOGDW1;

CREATE DATABASE BLOGDW1;

CREATE TABLE USUARIO (ID INT NOT NULL AUTO_INCREMENT, NOME VARCHAR(64) NOT NULL, SOBRENOME VARCHAR(64) NOT NULL, TELEFONE VARCHAR(11) NOT NULL, LOGIN VARCHAR(64) NOT NULL, SENHA VARCHAR(64) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE POSTAGEM (ID INT NOT NULL AUTO_INCREMENT, TEXTO LONGTEXT, AUTOR INT NOT NULL, DATA DATETIME DEFAULT CURRENT_TIMESTAMP ON, PRIMARY KEY (ID), FOREIGN KEY (AUTOR) REFERENCES USUARIO(ID));
