DROP DATABASE BLOGDW1;

CREATE DATABASE BLOGDW1;

CREATE TABLE USUARIO (ID INT NOT NULL AUTO_INCREMENT, NOME VARCHAR(64) NOT NULL, SOBRENOME VARCHAR(64) NOT NULL, TELEFONE VARCHAR(11) NOT NULL, LOGIN VARCHAR(64) NOT NULL, SENHA VARCHAR(64) NOT NULL, ADMIN BOOLEAN DEFAULT TRUE, PRIMARY KEY (ID));

CREATE TABLE POSTAGEM (ID INT NOT NULL AUTO_INCREMENT,TITULO VARCHAR(64) NOT NULL, TEXTO LONGTEXT, AUTOR INT NOT NULL, DATA DATETIME DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (ID), FOREIGN KEY (AUTOR) REFERENCES USUARIO(ID));

CREATE TABLE COMENTARIO (ID INT NOT NULL AUTO_INCREMENT, AUTOR INT NOT NULL, TEXTO LONGTEXT NOT NULL, DATA DATETIME DEFAULT CURRENT_TIMESTAMP, IDPOSTAGEM INT NOT NULL, PRIMARY KEY(ID), FOREIGN KEY (AUTOR) REFERENCES USUARIO(ID), FOREIGN KEY (IDPOSTAGEM) REFERENCES POSTAGEM(ID));

INSERT INTO USUARIO (NOME, SOBRENOME, TELEFONE, LOGIN, SENHA) VALUES ('ERINALDO', 'PEREIRA', '9999-9999', 'ERINALDO', 'PEREIRA');

INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('TITULO TESTE', 'TEXTO PARA TESTE DO BLOG', 1);

INSERT INTO POSTAGEM (TITULO, TEXTO, AUTOR) VALUES ('TITULO TESTE', 'TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, TEXTO PARA TESTE DO BLOG, ', 1);
